#!/usr/bin/env elixir
Code.require_file("cort_tooling.ex", __DIR__)

defmodule BuildSubset7FNotifyTransitionCasesHeader do
  @default_scenarios Path.expand("../fixtures/control/subset7f_notify_state_transition_cases_v1.json", __DIR__)
  @default_output Path.expand("../cort-fx/tests/generated/subset7f_notify_transition_cases.h", __DIR__)

  def main(argv) do
    options =
      CortTooling.parse_args!(argv,
        scenarios: :string,
        output: :string
      )

    scenarios_path = CortTooling.string_flag(options, :scenarios) || @default_scenarios
    output_path = CortTooling.string_flag(options, :output) || @default_output

    scenarios = load_scenarios!(scenarios_path)
    CortTooling.write_text!(output_path, render_header(scenarios))
  rescue
    error in [ArgumentError, File.Error, ErlangError, RuntimeError] ->
      CortTooling.usage_and_exit!(Exception.message(error))
  end

  defp load_scenarios!(path) do
    data = CortTooling.read_json!(path)
    cases = Map.get(data, "cases")

    unless is_list(cases) do
      raise ArgumentError, "#{path} does not contain a top-level cases array"
    end

    data
  end

  defp render_header(scenarios) do
    body =
      scenarios
      |> Map.fetch!("cases")
      |> Enum.sort_by(&fetch_string!(&1, "name"))
      |> Enum.map_join("\n", &render_case/1)

    """
    #ifndef FX_SUBSET7F_NOTIFY_TRANSITION_CASES_H
    #define FX_SUBSET7F_NOTIFY_TRANSITION_CASES_H

    /* Generated by tools/build_subset7f_notify_transition_cases_header.exs. */

    static const struct FXSubset7FTransitionCaseMeta kFXSubset7FTransitionCases[] = {
    #{body}
    };

    static const size_t kFXSubset7FTransitionCaseCount =
        sizeof(kFXSubset7FTransitionCases) / sizeof(kFXSubset7FTransitionCases[0]);

    #endif
    """
  end

  defp render_case(case_data) do
    cached = Map.get(case_data, "cached_registration")

    """
        {
            .name = #{c_string(fetch_string!(case_data, "name"))},
            .outcome_case_name = #{c_string(fetch_string!(case_data, "outcome_case"))},
            .operation = #{operation_constant(fetch_string!(case_data, "operation"))},
            .hasCachedRegistration = #{c_bool(is_map(cached))},
            .cachedSessionID = #{c_nullable_string(cached && Map.get(cached, "session_id"))},
            .cachedScope = #{c_nullable_string(cached && Map.get(cached, "scope"))},
            .cachedName = #{c_nullable_string(cached && Map.get(cached, "name"))},
            .cachedBindingID = #{c_nullable_string(cached && Map.get(cached, "binding_id"))},
            .cachedToken = #{c_integer(cached && Map.get(cached, "token"))},
            .cachedLastSeenGeneration = #{c_integer(cached && Map.get(cached, "last_seen_generation"))},
            .cachedFirstCheckPending = #{c_bool(cached && Map.get(cached, "first_check_pending"))}
        },
    """
  end

  defp operation_constant("registration_store"), do: "_FXCFControlNotifyTransitionOperationRegistrationStore"
  defp operation_constant("registration_update"), do: "_FXCFControlNotifyTransitionOperationRegistrationUpdate"
  defp operation_constant("check"), do: "_FXCFControlNotifyTransitionOperationCheck"
  defp operation_constant("cancel"), do: "_FXCFControlNotifyTransitionOperationCancel"
  defp operation_constant("get_state"), do: "_FXCFControlNotifyTransitionOperationGetState"
  defp operation_constant("is_valid_token"), do: "_FXCFControlNotifyTransitionOperationIsValidToken"
  defp operation_constant(other), do: raise(ArgumentError, "unsupported 7F operation #{inspect(other)}")

  defp c_string(value) when is_binary(value) do
    escaped =
      value
      |> String.replace("\\", "\\\\")
      |> String.replace("\"", "\\\"")
      |> String.replace("\n", "\\n")
      |> String.replace("\r", "\\r")
      |> String.replace("\t", "\\t")

    ~s("#{escaped}")
  end

  defp c_nullable_string(nil), do: "NULL"
  defp c_nullable_string(value) when is_binary(value), do: c_string(value)

  defp c_integer(nil), do: "0"
  defp c_integer(value) when is_integer(value), do: Integer.to_string(value)

  defp c_bool(true), do: "true"
  defp c_bool(false), do: "false"
  defp c_bool(nil), do: "false"

  defp fetch_string!(map, key) when is_map(map) do
    case Map.get(map, key) do
      value when is_binary(value) and value != "" -> value
      _ -> raise ArgumentError, "missing or invalid string field #{inspect(key)}"
    end
  end
end

BuildSubset7FNotifyTransitionCasesHeader.main(System.argv())
