#!/usr/bin/env elixir
Code.require_file("cort_tooling.ex", __DIR__)

defmodule BuildSubset7AControlPacketCasesHeader do
  @default_accept_payload Path.expand("../fixtures/control/bplist_packet_corpus_v1.json", __DIR__)
  @default_accept_source Path.expand("../fixtures/control/bplist_packet_corpus_v1.source.json", __DIR__)
  @default_reject_payload Path.expand("../fixtures/control/bplist_packet_rejection_corpus_v1.json", __DIR__)
  @default_expected Path.expand("../fixtures/control/subset7a_control_packet_expected_v1.json", __DIR__)
  @default_output Path.expand("../cort-fx/tests/generated/subset7a_control_packet_cases.h", __DIR__)

  def main(argv) do
    options =
      CortTooling.parse_args!(argv,
        accept_payload: :string,
        accept_source: :string,
        reject_payload: :string,
        expected: :string,
        output: :string
      )

    accept_payload_path = CortTooling.string_flag(options, :accept_payload) || @default_accept_payload
    accept_source_path = CortTooling.string_flag(options, :accept_source) || @default_accept_source
    reject_payload_path = CortTooling.string_flag(options, :reject_payload) || @default_reject_payload
    expected_path = CortTooling.string_flag(options, :expected) || @default_expected
    output_path = CortTooling.string_flag(options, :output) || @default_output

    header =
      build_header!(
        accept_payload_path,
        accept_source_path,
        reject_payload_path,
        expected_path
      )

    CortTooling.write_text!(output_path, header)
  rescue
    error in [ArgumentError, File.Error, ErlangError, RuntimeError] ->
      CortTooling.usage_and_exit!(Exception.message(error))
  end

  defp build_header!(accept_payload_path, accept_source_path, reject_payload_path, expected_path) do
    accept_payload = CortTooling.read_json!(accept_payload_path)
    accept_source = CortTooling.read_json!(accept_source_path)
    reject_payload = CortTooling.read_json!(reject_payload_path)
    expected = CortTooling.read_json!(expected_path)

    expect_mode!(accept_payload, "accept", accept_payload_path)
    expect_mode!(accept_source, "accept", accept_source_path)
    expect_mode!(reject_payload, "reject", reject_payload_path)

    expected_results =
      expected
      |> Map.fetch!("results")
      |> Map.new(fn result -> {Map.fetch!(result, "name"), result} end)

    accept_source_packets =
      accept_source
      |> Map.fetch!("cases")
      |> Map.new(fn case_data -> {Map.fetch!(case_data, "id"), Map.fetch!(case_data, "packet")} end)

    accept_cases =
      accept_payload
      |> Map.fetch!("cases")
      |> Enum.map(fn case_data ->
        name = Map.fetch!(case_data, "id")
        source_packet =
          Map.get(accept_source_packets, name) ||
            raise(ArgumentError, "missing accept source packet for #{name}")

        expected_result =
          Map.get(expected_results, name) ||
            raise(ArgumentError, "missing expected result for #{name}")

        emit_accept_case(case_data, source_packet, expected_result)
      end)

    reject_cases =
      reject_payload
      |> Map.fetch!("cases")
      |> Enum.map(fn case_data ->
        name = Map.fetch!(case_data, "id")

        expected_result =
          Map.get(expected_results, name) ||
            raise(ArgumentError, "missing expected result for #{name}")

        emit_reject_case(case_data, expected_result)
      end)

    cases =
      (accept_cases ++ reject_cases)
      |> Enum.sort_by(& &1.case_name)

    """
    #ifndef FX_SUBSET7A_CONTROL_PACKET_CASES_H
    #define FX_SUBSET7A_CONTROL_PACKET_CASES_H

    /* Generated by tools/build_subset7a_control_packet_cases_header.exs. */

    #{Enum.map_join(cases, "\n", & &1.definitions)}

    static const struct FXSubset7ACase kFXSubset7ACases[] = {
    #{Enum.map_join(cases, ",\n", &("  " <> &1.case_initializer))}
    };

    static const size_t kFXSubset7ACaseCount = sizeof(kFXSubset7ACases) / sizeof(kFXSubset7ACases[0]);

    #endif
    """
  end

  defp expect_mode!(data, expected_mode, path) do
    actual = Map.get(data, "validation_mode")

    if actual != expected_mode do
      raise ArgumentError, "#{path} has validation_mode=#{inspect(actual)}, expected #{inspect(expected_mode)}"
    end
  end

  defp emit_accept_case(case_data, source_packet, expected_result) do
    case_name = Map.fetch!(case_data, "id")
    ident = case_identifier(case_name)
    payload_name = "kFXSubset7A#{ident}Payload"
    payload_bytes = decode_payload!(case_data)
    {template_defs, nodes_name, root_index} = emit_template(ident, source_packet)

    definitions =
      [
        emit_byte_array(payload_name, payload_bytes),
        template_defs
      ]
      |> Enum.join("\n\n")

    initializer = """
    {
        .name = #{c_string(case_name)},
        .validation_mode = FXSubset7AValidationAccept,
        .kind = #{packet_kind(Map.fetch!(case_data, "kind"))},
        .payload = #{payload_name},
        .payload_length = sizeof(#{payload_name}),
        .expected_primary_value_text = #{c_string(Map.fetch!(expected_result, "primary_value_text"))},
        .expected_alternate_value_text = #{c_string(Map.fetch!(expected_result, "alternate_value_text"))},
        .accept_nodes = #{nodes_name},
        .accept_root_index = #{root_index}u,
        .reject_kind = 0,
        .reject_text = NULL,
        .reject_version = 0
    }\
    """

    %{
      case_name: case_name,
      definitions: definitions,
      case_initializer: initializer
    }
  end

  defp emit_reject_case(case_data, expected_result) do
    case_name = Map.fetch!(case_data, "id")
    ident = case_identifier(case_name)
    payload_name = "kFXSubset7A#{ident}Payload"
    payload_bytes = decode_payload!(case_data)
    expected_error = Map.fetch!(case_data, "expected_error")

    {reject_kind, reject_text, reject_version} =
      case Map.fetch!(expected_error, "type") do
        "missing_key" ->
          {"FXSubset7ARejectMissingKey", Map.fetch!(expected_error, "key"), 0}

        "unsupported_version" ->
          {"FXSubset7ARejectUnsupportedVersion", nil, Map.fetch!(expected_error, "version")}

        "invalid_packet" ->
          {"FXSubset7ARejectInvalidPacket", Map.fetch!(expected_error, "detail"), 0}

        other ->
          raise ArgumentError, "unsupported reject type #{inspect(other)}"
      end

    definitions = emit_byte_array(payload_name, payload_bytes)

    initializer = """
    {
        .name = #{c_string(case_name)},
        .validation_mode = FXSubset7AValidationReject,
        .kind = #{packet_kind(Map.fetch!(case_data, "kind"))},
        .payload = #{payload_name},
        .payload_length = sizeof(#{payload_name}),
        .expected_primary_value_text = #{c_string(Map.fetch!(expected_result, "primary_value_text"))},
        .expected_alternate_value_text = #{c_string(Map.fetch!(expected_result, "alternate_value_text"))},
        .accept_nodes = NULL,
        .accept_root_index = 0u,
        .reject_kind = #{reject_kind},
        .reject_text = #{if reject_text == nil, do: "NULL", else: c_string(reject_text)},
        .reject_version = #{reject_version}
    }\
    """

    %{
      case_name: case_name,
      definitions: definitions,
      case_initializer: initializer
    }
  end

  defp emit_template(ident, source_packet) do
    state = %{defs: [], nodes: []}
    {state, root_index} = build_node(source_packet, "kFXSubset7A#{ident}", state)
    nodes_name = "kFXSubset7A#{ident}Nodes"

    node_defs =
      state.nodes
      |> Enum.with_index()
      |> Enum.map_join(",\n", fn {node, index} ->
        "    [#{index}] = #{emit_node_initializer(node)}"
      end)

    defs =
      (state.defs ++ [
         """
         static const struct FXSubset7ATemplateNode #{nodes_name}[] = {
         #{node_defs}
         };
         """
       ])
      |> Enum.join("\n\n")

    {defs, nodes_name, root_index}
  end

  defp build_node(value, _prefix, state) when is_nil(value) do
    append_node(state, %{kind: "FXSubset7ATemplateNil"})
  end

  defp build_node(value, _prefix, state) when is_binary(value) do
    append_node(state, %{kind: "FXSubset7ATemplateString", text: value})
  end

  defp build_node(value, _prefix, state) when is_integer(value) do
    append_node(state, %{kind: "FXSubset7ATemplateInteger", integer_value: value})
  end

  defp build_node(value, _prefix, state) when is_float(value) do
    append_node(state, %{kind: "FXSubset7ATemplateDouble", double_value: value})
  end

  defp build_node(value, _prefix, state) when is_boolean(value) do
    append_node(state, %{kind: "FXSubset7ATemplateBool", bool_value: value})
  end

  defp build_node(%{"$date" => text}, _prefix, state) when is_binary(text) do
    append_node(state, %{kind: "FXSubset7ATemplateDate", text: text})
  end

  defp build_node(%{"$data_utf8" => text}, prefix, state) when is_binary(text) do
    bytes_name = "#{prefix}DataBytes"
    bytes = :binary.bin_to_list(text)

    state = add_def(state, emit_byte_array(bytes_name, bytes))
    append_node(state, %{kind: "FXSubset7ATemplateData", bytes_name: bytes_name, byte_count: length(bytes)})
  end

  defp build_node(%{"$data_base64" => text}, prefix, state) when is_binary(text) do
    bytes_name = "#{prefix}DataBytes"
    bytes = Base.decode64!(text)

    state = add_def(state, emit_byte_array(bytes_name, :binary.bin_to_list(bytes)))
    append_node(state, %{kind: "FXSubset7ATemplateData", bytes_name: bytes_name, byte_count: byte_size(bytes)})
  end

  defp build_node(value, prefix, state) when is_list(value) do
    {state, item_indices} =
      Enum.with_index(value)
      |> Enum.reduce({state, []}, fn {item, index}, {acc_state, indices} ->
        {next_state, node_index} = build_node(item, "#{prefix}Item#{index}", acc_state)
        {next_state, indices ++ [node_index]}
      end)

    if item_indices == [] do
      append_node(state, %{kind: "FXSubset7ATemplateArray", items_name: nil, child_count: 0})
    else
      items_name = "#{prefix}Items"

      state =
        add_def(
          state,
          """
          static const size_t #{items_name}[] = {#{Enum.map_join(item_indices, ", ", &"#{&1}u")}};
          """
        )

      append_node(state, %{kind: "FXSubset7ATemplateArray", items_name: items_name, child_count: length(item_indices)})
    end
  end

  defp build_node(value, prefix, state) when is_map(value) do
    sorted_entries = value |> Map.keys() |> Enum.sort() |> Enum.map(&{&1, Map.fetch!(value, &1)})

    {state, entries} =
      Enum.reduce(sorted_entries, {state, []}, fn {key, child}, {acc_state, acc_entries} ->
        {next_state, node_index} = build_node(child, "#{prefix}#{sanitize(key)}", acc_state)
        {next_state, acc_entries ++ [%{key: key, node_index: node_index}]}
      end)

    if entries == [] do
      append_node(state, %{kind: "FXSubset7ATemplateObject", entries_name: nil, child_count: 0})
    else
      entries_name = "#{prefix}Entries"

      state =
        add_def(
          state,
          """
          static const struct FXSubset7AObjectEntry #{entries_name}[] = {
          #{Enum.map_join(entries, ",\n", fn entry -> "    {#{c_string(entry.key)}, #{entry.node_index}u}" end)}
          };
          """
        )

      append_node(state, %{kind: "FXSubset7ATemplateObject", entries_name: entries_name, child_count: length(entries)})
    end
  end

  defp append_node(state, node) do
    index = length(state.nodes)
    {%{state | nodes: state.nodes ++ [node]}, index}
  end

  defp add_def(state, definition) do
    %{state | defs: state.defs ++ [definition]}
  end

  defp emit_node_initializer(node) do
    fields = [
      ".kind = #{node.kind}",
      ".text = #{emit_nullable_string(Map.get(node, :text))}",
      ".integer_value = #{Map.get(node, :integer_value, 0)}",
      ".double_value = #{emit_double(Map.get(node, :double_value, 0.0))}",
      ".bool_value = #{if Map.get(node, :bool_value, false), do: "true", else: "false"}",
      ".entries = #{emit_nullable_symbol(Map.get(node, :entries_name))}",
      ".items = #{emit_nullable_symbol(Map.get(node, :items_name))}",
      ".child_count = #{Map.get(node, :child_count, 0)}u",
      ".bytes = #{emit_nullable_symbol(Map.get(node, :bytes_name))}",
      ".byte_count = #{Map.get(node, :byte_count, 0)}u"
    ]

    "{#{Enum.join(fields, ", ")}}"
  end

  defp emit_double(value) when is_float(value) do
    :erlang.float_to_binary(value, [:compact, decimals: 17])
  end

  defp emit_nullable_symbol(nil), do: "NULL"
  defp emit_nullable_symbol(symbol), do: symbol

  defp emit_nullable_string(nil), do: "NULL"
  defp emit_nullable_string(text), do: c_string(text)

  defp emit_byte_array(name, bytes) do
    values =
      bytes
      |> Enum.map_join(", ", fn byte -> "0x" <> String.pad_leading(Integer.to_string(byte, 16), 2, "0") <> "u" end)

    "static const UInt8 #{name}[] = {#{values}};"
  end

  defp decode_payload!(case_data) do
    case_data
    |> Map.fetch!("payload_base64")
    |> Base.decode64!()
    |> :binary.bin_to_list()
  end

  defp packet_kind("request"), do: "FXSubset7ARequest"
  defp packet_kind("response"), do: "FXSubset7AResponse"
  defp packet_kind(other), do: raise(ArgumentError, "unsupported packet kind #{inspect(other)}")

  defp case_identifier(name) do
    name
    |> String.split(~r/[^A-Za-z0-9]+/, trim: true)
    |> Enum.map(&String.capitalize/1)
    |> Enum.join()
  end

  defp sanitize(name) do
    name
    |> String.replace(~r/[^A-Za-z0-9]/, "_")
    |> String.replace(~r/_+/, "_")
  end

  defp c_string(text) do
    encoded =
      text
      |> :json.encode()
      |> IO.iodata_to_binary()

    encoded
  end
end

BuildSubset7AControlPacketCasesHeader.main(System.argv())
